const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "GodFather API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:5000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    securityDefinitions: {
        bearerAuth: {
          type: 'apiKey',
          name: 'Authorization',
          scheme: 'bearer',
          in: 'header',
        },
    },
    security: [
        {
            bearerAuth: []
        }
    ],
    definitions: {
        Character: {
            character: {
                status: {
                    pointsAvailable: 1000,
                    atk: 21,
                    res: 42,
                    lck: 999,
                    rsl: 23
                },
                leveling: {
                    xp: 7,
                    level: 1,
                    upXp: 10
                },
                activeMission: {
                    missionId: {
                        _id: 0,
                        name: "Fender Ketchup",
                        description: "Follow the damn train CJ",
                        sender: "Big Smoke",
                        xp: 50,
                        time: 1,
                        __v: 0
                    },
                    missionStartTime: 1620329842319
                },
                _id: 0,
                picture: "https://dd2t.github.io/psw/images/character/character-images/mafia-luffy.jpg",
                name: "Backend working",
                wins: 42,
                losses: 23,
                rankId: 0,
                __v: 0
            }
        },
        GoldOffers: {
            offerArray: [
                {
                    _id: 0,
                    picture: "https://dd2t.github.io/psw/images/gold-shop/description-images/1200g-300px.jpg",
                    description: "Don's heritage",
                    link: "www.google.com",
                    value: 1200,
                    price: 200,
                    discount: 20,
                    __v: 0
                }
            ]
        },
        Missions: {
            missionList: [
                {
                    _id: 0,
                    name: "Fender Ketchup",
                    description: "Follow the damn train CJ",
                    sender: "Big Smoke",
                    xp: 50,
                    time: 1,
                    __v: 0
                }
            ]
        },
        SignUp: {
            success: true,
            status: "Registration Successful!"
        },
        SignUpErro: {
            err: {
                name: "UserExistsError",
                message: "A user with the given username is already registered"
            }
        },
        Login: {
            username: "any",
            password: "any"
        },
        LoginResposta: {
            token: "<Bearer Token>",
            username: "any"
        },
        IncrementStatus: {
            status: {
                pointsAvailable: 999,
                atk: 22,
                res: 42,
                lck: 999,
                rsl: 23
            }
        },
        Logout: {
            token: "<Bearer Token>"
        }
    }
}

const outputFile = './swagger_output.json'
const endpointsFiles = ['./app.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app')           // Your project's root file
})